In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer

In [2]:
# Load sample data (which includes the numerical labels)
df = pd.read_csv("./data/sample_doc_vec_labels.csv")
df

title  \
0                    №211 みずにながす、がおー。   
1                                 見送り   
2                     Eテレ『趣味どきっ！』が面白い   
3                 新しい服はしばらく買わないと決めてみて   
4                               蓮の花言葉   
...                               ...   
2343                         レッツダンス❗️   
2344      Creepy Nutsの武道館ライブを、配信で見たよ♪   
2345                    珍しいチューナーを見つけた   
2346  パピコクレさんに捧ぐアリア（歌：Paprikachordさん）   
2347        今をときめく現代アーティストとは？【自己紹介続き】   

                                                content  \
0     今日は午前中だけ仕事して、午後医者に行き、夕方はホームレスのお友達からお寿司をおごってもらっ...   
1     父も、母も、もう他界してしばらくが経つ。私も、もう、いい歳で。父も母も、生きていればそれなり...   
2     　最近、たまたま観たのですが『趣味どきっ！』の“スゴ楽” 家事への道シリーズが良かったんです...   
3     新しい服を買わないようにしようと決めて3年ほどたった。3年前ぐらいに、断捨離とか、家の整理と...   
4     父方の祖父母の家には、伯父と伯母と従兄弟が一緒に暮らしていて、台所には冷蔵庫と茶箪笥が2台ず...   
...                                                 ...   
2343  今回、ナゴコンの皆さんと、沢山の方々に助けて頂いて、出来上がって来ました。”緑文化小劇場＆ナ...   
2344  　　12日夜、Creepy　Nuts（クリーピーナッツ）という、ヒップホップのグループの武道...   
2345  ども、キャンピングミュージシャンの山木将平です。　最近ギターのチューナーを無くしてしまいどー...   
2346  「パピコクレさんに捧ぐアリア」をPaprikachordさんに歌っていただきました。「パピコ...   
2347  こんばんは。なぜ、こんばんは、って？それはこの記事を読めばわかるかもしれないです。さて、今回...   

                                                   tags  \
0                                             ['#毎日更新']   
1     ['#日記', '#エッセイ', '#母', '#父', '#ほぼ毎日note', '#やさ...   
2                     ['#毎日note', '#習慣', '#テレビ', '#掃除']   
3                                              ['#断捨離']   
4                  ['#介護', '#母', '#認知症', '#父', '#引っ越し']   
...                                                 ...   
2343                                    ['#ピアノ', '#映像']   
2344                                  ['#音楽', '#ライブ配信']   
2345                               ['#ギター', '#ミュージシャン']   
2346                         ['#音楽', '#DTM', '#オリジナル曲']   
2347                                          ['#自己紹介']   

                                                doc_vec  \
0     [-0.6413622315797844, -0.02762089093218069, -0...   
1     [-0.21704280540967982, 0.06023082480144997, -0...   
2     [-0.6624432352820425, -0.054146641178606014, -...   
3     [-0.6314828735735987, -0.09158760018281703, -0...   
4     [-0.522198764722776, -0.01959150434377851, -0....   
...                                                 ...   
2343  [-0.8237114698033441, -0.12204698043113404, -0...   
2344  [-0.48791739515120713, -0.38404660005594643, -...   
2345  [-0.9868878505362549, -0.032979069012369897, -...   
2346  [-0.9321060173370889, -0.046223862741706555, -...   
2347  [-0.5622327147551426, -0.12416846316262353, -0...   

                             labels  
0                               [9]  
1     [0, 1, 565, 1068, 1146, 1382]  
2                [3, 160, 478, 779]  
3                             [421]  
4       [199, 565, 890, 1068, 1302]  
...                             ...  
2343                    [169, 1051]  
2344                       [8, 708]  
2345                    [148, 1399]  
2346                  [8, 103, 488]  
2347                           [27]  

[2348 rows x 5 columns]

In [3]:
# Getting and formatting the inputs (doc_vec) and outputs (multilabel) from dataframe 
X = np.array([np.array(eval(elem)) for elem in df["doc_vec"]])
Y = np.array([eval(elem) for elem in df["labels"]])
Y = MultiLabelBinarizer(classes=range(2000)).fit_transform(Y)
print(X)
print(Y)

[[-0.64136223 -0.02762089 -0.31077059 ... -0.29829604 -0.53742901
   0.18948011]
 [-0.21704281  0.06023082 -0.55525767 ... -0.31878226 -0.48156569
  -0.25063461]
 [-0.66244324 -0.05414664 -0.38273322 ... -0.5921418  -0.41440249
   0.13317313]
 ...
 [-0.98688785 -0.03297907 -0.57405516 ... -0.70934571 -0.44303308
  -0.01264584]
 [-0.93210602 -0.04622386 -0.6457347  ... -0.4526942  -0.18084227
   0.18225742]
 [-0.56223271 -0.12416846 -0.67268819 ... -0.5615323  -0.30514376
   0.01940162]]
[[0 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


<ipython-input-3-194b11312ddd>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Y = np.array([eval(elem) for elem in df["labels"]])


In [4]:
print(X.shape,Y.shape)

(2348, 200) (2348, 2000)


In [5]:
# Separating the train and test data
# It is commentend for now since the data size is small
x_train, x_test,y_train, y_test = train_test_split(X,Y)

In [24]:
# Defining our model (in this case I am using a Gaussian Naive Bayes Classifier) 
# and updating it for multilabeling
model = OneVsRestClassifier(GaussianNB())
# Fitting the model with data
model.fit(x_train,y_train)

/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 33 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 57 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 74 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 91 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 94 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-

OneVsRestClassifier(estimator=GaussianNB())

In [25]:
# Testing the model
y_pred = model.predict(x_test)
y_pred_proba = model.predict_proba(x_test)

In [26]:
print(y_pred)
print(y_test)
idx = 1
N = 5
a = np.where(y_test[idx] == 1)
print(a)
print(y_pred_proba[idx].argsort()[-5:][::-1])

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(array([367]),)
[ 45 271 446  10 454]


In [27]:
# Function to get the more likely N labels
def predict(model,x,N=5):
    tmp = model.predict_proba(x)
    pred = np.array([elem.argsort()[-N:][::-1] for elem in tmp])
    return pred
def single_predict(model,x,N=5):
    tmp = model.predict_proba(np.array([x]))
    pred_idx = tmp[0].argsort()[-N:][::-1]
    pred_prob = tmp[0][pred_idx]
    return pred_idx,pred_prob

In [28]:
# Testing the model (with predict function)
m = 10 # number of test cases to take
pred = predict(model,x_test[:m])
test = [list(np.where(elem==1)[0]) for elem in y_test[:m]]
print(pred)
for elem in test:
    print(elem)

[[  48  164    5  252   68]
 [  45  271  446   10  454]
 [  37  109 1325   51   44]
 [  31  253  163   45   79]
 [  36  277   27   44  904]
 [ 517   67  102  109   44]
 [  38  904  120   59  160]
 [   0   20   70   48   80]
 [ 442  109   40  174 1661]
 [ 610   62    0   86    1]]
[0, 3, 5, 9, 17, 548, 984, 1337, 1499]
[367]
[109, 1325]
[707, 1117, 1718]
[44, 320, 365, 582, 995]
[1, 109, 142, 366, 517]
[36, 37, 219, 221, 370, 916]
[1, 24, 226, 874, 1285, 1914]
[3, 39, 174, 442, 1572, 1661]
[3, 44]


In [29]:
tags = pd.read_csv("./data/2000tags.csv")
tags = tags["タグ"]

In [45]:
from tabulate import tabulate
# Testing the model (with single predict function)
idx = 189
#x_test1 = eval(df["doc_vec"][idx])
#y_test1 = eval(df["labels"][idx])
x_test1 = x_test[idx]
y_test1 = list(np.where(y_test[idx])[0])
pred,prob = single_predict(model,x_test1,N=10)
test = y_test1
pred = list(pred)
print("predicted indexes: ",pred)
print("original indexes: ",test)
lp = len(pred)
lt = len(test)
if lp < lt:
    pred = pred + [""]*(lt-lp)
elif lt < lp:
    test = test + [""]*(lp - lt)
#print("Predicted Tags \t status \t Original Tags")
tmp = []
for i in pred:
    status = "          "
    if i in test:
        j = i
        status = "<- match ->"
    else:
        for k in test:
            if k not in pred:
                j = k
                break
    #print("%s \t %s \t %s".format(i if i=="" else tags[i],status,j if j == "" else tags[j]))
    tmp.append([i if i=="" else tags[i],status,j if j == "" else tags[j]])
    test.pop(test.index(j))
print(tabulate(tmp,headers=["Predicted Tags","status","Original Tags"]))

predicted indexes:  [10, 9, 39, 17, 12, 15, 104, 3, 163, 6]
original indexes:  [3, 9, 10, 52, 95]
Predicted Tags    status       Original Tags
----------------  -----------  ---------------
#ビジネス         <- match ->  #ビジネス
#毎日更新         <- match ->  #毎日更新
#note毎日更新                  #本
#毎日投稿                      #サッカー
#note
#仕事
#スポーツ
#毎日note         <- match ->  #毎日note
#アメリカ
#コラム


In [20]:
#df["content"][idx]

'かつてロシアの政治家スターリンはこう言った。『一人の人間の死は悲劇だが、数百万人の人間の死は統計上の数字でしかない』と。そしてこうも言い残している。『愛とか友情などというものはすぐに壊れるが、恐怖は長続きする』※注）このストーリーは全てフィクションです-----------------------------------研究員「完成しました。このウィルスの感染率は非常に高く、発生させればもう止めることはできません。あっという間に全世界に拡散することでしょう」所長「致死率は？」研究員「低く設定してあります。ウィルス保持者が死んでしまうと媒介できませんからね。その意味で潜伏期間も長くしました。ウィルス保持者は知らないうちに媒介者となり、そして長く媒介をし続けることになります」所長「ワクチンも完成してるのだな？」研究員「はい、もちろんです。ワクチンの予防効果は99％です」所長「それでいい」研究員「しかし所長、このウィルスとワクチンをどう使うのですか？まさか戦争に…」所長「君。世の中には知らない方がいいこともあるのだよ」F社はアメリカ合衆国ニューヨーク州に本社を置く製薬会社である。2019年の医薬品売上高では世界第2位を誇る。しかしF社には常に黒い噂もつきまとう。2016年10月、F社が、医療従事者を世界中に派遣するチャリティ団体に対して100万本のワクチンを寄付すると提案した。ところが医師団は、その提案を拒否する。F社は肺炎のワクチンの最終製品だけでなく、製造過程を含む複数の特許を所有しており、競合起業が参入できない、いわば独占状態でワクチンの値段を高騰させており、人命を救うためのワクチンによって、F社は莫大な利益を上げていると各方面から非難されていたのだ。その他にも、薬の開発の前に病気を開発しているとも・・・-----------------------------------所長「例のウィルスとワクチンですが、完成いたしました。こちらがその資料です」政治家「よくやった。発生時から1年間、ワクチンを使わなかった場合の推定死亡者数はどれくらいだ？」所長「100～150万人といったところでしょう」政治家「そうか。まあいいだろう。ワクチン使用時の予防率はどれくらいだ？」所長「99%です」政治家「それでは予防率を落としたワクチンをもう一種類作ってくれ。そうだな80～90%くら