In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer

In [6]:
# Load sample data (which includes the numerical labels)
df = pd.read_csv("./data/sample_doc_vec_labels.csv")
df

title  \
0                    №211 みずにながす、がおー。   
1                                 見送り   
2                     Eテレ『趣味どきっ！』が面白い   
3                 新しい服はしばらく買わないと決めてみて   
4                               蓮の花言葉   
...                               ...   
2343                         レッツダンス❗️   
2344      Creepy Nutsの武道館ライブを、配信で見たよ♪   
2345                    珍しいチューナーを見つけた   
2346  パピコクレさんに捧ぐアリア（歌：Paprikachordさん）   
2347        今をときめく現代アーティストとは？【自己紹介続き】   

                                                content  \
0     今日は午前中だけ仕事して、午後医者に行き、夕方はホームレスのお友達からお寿司をおごってもらっ...   
1     父も、母も、もう他界してしばらくが経つ。私も、もう、いい歳で。父も母も、生きていればそれなり...   
2     　最近、たまたま観たのですが『趣味どきっ！』の“スゴ楽” 家事への道シリーズが良かったんです...   
3     新しい服を買わないようにしようと決めて3年ほどたった。3年前ぐらいに、断捨離とか、家の整理と...   
4     父方の祖父母の家には、伯父と伯母と従兄弟が一緒に暮らしていて、台所には冷蔵庫と茶箪笥が2台ず...   
...                                                 ...   
2343  今回、ナゴコンの皆さんと、沢山の方々に助けて頂いて、出来上がって来ました。”緑文化小劇場＆ナ...   
2344  　　12日夜、Creepy　Nuts（クリーピーナッツ）という、ヒップホップのグループの武道...   
2345  ども、キャンピングミュージシャンの山木将平です。　最近ギターのチューナーを無くしてしまいどー...   
2346  「パピコクレさんに捧ぐアリア」をPaprikachordさんに歌っていただきました。「パピコ...   
2347  こんばんは。なぜ、こんばんは、って？それはこの記事を読めばわかるかもしれないです。さて、今回...   

                                                   tags  \
0                                             ['#毎日更新']   
1     ['#日記', '#エッセイ', '#母', '#父', '#ほぼ毎日note', '#やさ...   
2                     ['#毎日note', '#習慣', '#テレビ', '#掃除']   
3                                              ['#断捨離']   
4                  ['#介護', '#母', '#認知症', '#父', '#引っ越し']   
...                                                 ...   
2343                                    ['#ピアノ', '#映像']   
2344                                  ['#音楽', '#ライブ配信']   
2345                               ['#ギター', '#ミュージシャン']   
2346                         ['#音楽', '#DTM', '#オリジナル曲']   
2347                                          ['#自己紹介']   

                                                doc_vec  \
0     [-0.6413622315797844, -0.02762089093218069, -0...   
1     [-0.21704280540967982, 0.06023082480144997, -0...   
2     [-0.6624432352820425, -0.054146641178606014, -...   
3     [-0.6314828735735987, -0.09158760018281703, -0...   
4     [-0.522198764722776, -0.01959150434377851, -0....   
...                                                 ...   
2343  [-0.8237114698033441, -0.12204698043113404, -0...   
2344  [-0.48791739515120713, -0.38404660005594643, -...   
2345  [-0.9868878505362549, -0.032979069012369897, -...   
2346  [-0.9321060173370889, -0.046223862741706555, -...   
2347  [-0.5622327147551426, -0.12416846316262353, -0...   

                             labels  
0                               [9]  
1     [0, 1, 565, 1068, 1146, 1382]  
2                [3, 160, 478, 779]  
3                             [421]  
4       [199, 565, 890, 1068, 1302]  
...                             ...  
2343                    [169, 1051]  
2344                       [8, 708]  
2345                    [148, 1399]  
2346                  [8, 103, 488]  
2347                           [27]  

[2348 rows x 5 columns]

In [201]:
# Getting and formatting the inputs (doc_vec) and outputs (multilabel) from dataframe 
X = np.array([np.array(eval(elem)) for elem in df["doc_vec"]])
Y = np.array([eval(elem) for elem in df["labels"]])
Y = MultiLabelBinarizer(classes=range(2000)).fit_transform(Y)
print(X)
print(Y)

[[-0.64136223 -0.02762089 -0.31077059 ... -0.29829604 -0.53742901
   0.18948011]
 [-0.21704281  0.06023082 -0.55525767 ... -0.31878226 -0.48156569
  -0.25063461]
 [-0.66244324 -0.05414664 -0.38273322 ... -0.5921418  -0.41440249
   0.13317313]
 ...
 [-0.98688785 -0.03297907 -0.57405516 ... -0.70934571 -0.44303308
  -0.01264584]
 [-0.93210602 -0.04622386 -0.6457347  ... -0.4526942  -0.18084227
   0.18225742]
 [-0.56223271 -0.12416846 -0.67268819 ... -0.5615323  -0.30514376
   0.01940162]]
[[0 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


<ipython-input-201-194b11312ddd>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Y = np.array([eval(elem) for elem in df["labels"]])


In [202]:
print(X.shape,Y.shape)

(2348, 200) (2348, 2000)


In [218]:
# Separating the train and test data
# It is commentend for now since the data size is small
x_train, x_test,y_train, y_test = train_test_split(X,Y)

In [204]:
# Defining our model (in this case I am using a Gaussian Naive Bayes Classifier) 
# and updating it for multilabeling
model = OneVsRestClassifier(GaussianNB())
# Fitting the model with data
model.fit(X,Y)

/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 33 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 57 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 74 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 91 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 94 is present in all training examples.
  warnings.warn("Label %s is present in all training examples." %
/opt/conda/lib/python3.8/site-

OneVsRestClassifier(estimator=GaussianNB())

In [219]:
# Testing the model
y_pred = model.predict(x_test)
y_pred_proba = model.predict_proba(x_test)

In [220]:
print(y_pred)
print(y_test)
idx = 1
N = 5
a = np.where(y_test[idx] == 1)
print(a)
print(y_pred_proba[idx].argsort()[-5:][::-1])

[[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]]
(array([ 121,  402, 1939]),)
[1941 1939   42  605  402]


In [221]:
# Function to get the more likely N labels
def predict(model,x,N=5):
    tmp = model.predict_proba(x)
    pred = np.array([elem.argsort()[-N:][::-1] for elem in tmp])
    return pred
def single_predict(model,x,N=5):
    tmp = model.predict_proba(np.array([x]))
    pred_idx = tmp[0].argsort()[-N:][::-1]
    pred_prob = tmp[0][pred_idx]
    return pred_idx,pred_prob

In [222]:
# Testing the model (with predict function)
m = 10 # number of test cases to take
pred = predict(model,x_test[:m])
test = [list(np.where(elem==1)[0]) for elem in y_test[:m]]
print(pred)
for elem in test:
    print(elem)

[[ 187  665  216  163  120]
 [1941 1939   42  605  402]
 [   5  252  244    0   48]
 [ 104  324  343   95  279]
 [ 152  534  142  610  503]
 [  40   37  904   69   50]
 [  38  882  576   36   90]
 [   2  163   19    9    0]
 [ 530  153  510 1334   67]
 [1517   20    1   80  161]]
[187, 216, 665]
[121, 402, 1939]
[0, 25, 52, 116, 180, 244]
[0, 76, 343]
[194, 534, 1763]
[36, 37]
[38, 576, 882]
[0, 2, 41, 356]
[3, 37, 153, 510, 530, 1334]
[0, 1, 14, 20, 205, 1146, 1517]


In [223]:
tags = pd.read_csv("./data/2000tags.csv")
tags = tags["タグ"]

In [256]:
from tabulate import tabulate
# Testing the model (with single predict function)
idx = 1144
x_test1 = eval(df["doc_vec"][idx])
y_test1 = eval(df["labels"][idx])

pred,prob = single_predict(model,x_test1,N=10)
test = y_test1
pred = list(pred)
print("predicted indexes: ",pred)
print("original indexes: ",test)
lp = len(pred)
lt = len(test)
if lp < lt:
    pred = pred + [""]*(lt-lp)
elif lt < lp:
    test = test + [""]*(lp - lt)
#print("Predicted Tags \t status \t Original Tags")
tmp = []
for i in pred:
    status = "          "
    if i in test:
        j = i
        status = "<- match ->"
    else:
        for k in test:
            if k not in pred:
                j = k
                break
    #print("%s \t %s \t %s".format(i if i=="" else tags[i],status,j if j == "" else tags[j]))
    tmp.append([i if i=="" else tags[i],status,j if j == "" else tags[j]])
    test.pop(test.index(j))
print(tabulate(tmp,headers=["Predicted Tags","status","Original Tags"]))

predicted indexes:  [924, 1783, 120, 581, 374, 10, 47, 545, 60, 219]
original indexes:  [10, 39, 219, 545, 924, 1783]
Predicted Tags    status       Original Tags
----------------  -----------  ---------------
#広島             <- match ->  #広島
#肩こり           <- match ->  #肩こり
#コロナ                        #note毎日更新
#転職活動
#働き方改革
#ビジネス         <- match ->  #ビジネス
#副業
#個人事業主       <- match ->  #個人事業主
#起業
#トレーニング     <- match ->  #トレーニング


In [257]:
df["content"][idx]

'大手企業が軒並み副業を解禁している今、電通は一部の正社員を業務委託契約に切り替え、個人事業主として働く制度を始めます。大手企業の新たな取り組みに様々なところで報道されています。\n\n\n電通、社員230人を個人事業主に\u3000新規事業創出ねらう\n\n\n電通は一部の正社員を業務委託契約に切り替え、「個人事業主」として働いてもらう制度を始める。まずは2021年1月から全体の3\n\n\nwww.nikkei.com\n\n\n\nしかし今回の電通の対応は、どう見ても人員整理の一貫としかみえません。これから新制度の適用も始まる中、わざわざ一度退職して業務委託契約をする理由は、早期退職を促した社員の一時的な補助と考えられます。その理由として、今回の対象が全職種の40代以上の社員が対象になっているからです。やっと役職に就いたところでの、実質的な早期退職への勧告は非情としか思えません。これは今までのように広告代理店が増収増益が非常に難しくなっており、社内の最適化が急務となっています。今まで大手企業で定年退職をして、退職金で老後を楽しもうと思っていた世代が、突然個人事業主として世の中に投げ出される訳です。もちろん成功する人も中にいますが、これから個人事業主はおすすめできません。2023年10月からインボイス制度が始まり、今までのような個人事業主のメリットがなくなり、業種によっては法人化しないと難しくなってきます。そのためには売上をある一定を確保しないといけません。これからフリーランスや個人事業主を始める人はよくインボイス制度を理解する必要があります。「人生、楽しんだもん勝ち！」【昨日の移動距離】151km朝ジムで背中・肩のトレーニング。帰宅後は在宅ワーク。午後から打合せで外出。来年ぐらいからコロナの影響が顕著に出そうだ。【2020年移動距離】26,824km#移動距離とクリエイティビティは比例する＜編集後記＞今日、明日は在宅で研修に参加しています。なかなか朝から夕方までずっと座って参加することが珍しく、初日にして肩が凝ってしまいました。ただ内容をしては人数も多くなってきたので、小グループでの会話が非常に有意義でした。様々な価値観を持った社員が増えているので、自分も柔軟に意見を受け入れないといけないことに気づきました。どんどん歳を重ねますが、時代の変化にも対応しないとビ