In [58]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer

In [4]:
# Load sample data (which includes the numerical labels)
df = pd.read_csv("./data/sample_doc_vec_labels.csv")
df

title  \
0                    №211 みずにながす、がおー。   
1                                 見送り   
2                     Eテレ『趣味どきっ！』が面白い   
3                 新しい服はしばらく買わないと決めてみて   
4                               蓮の花言葉   
...                               ...   
2343                         レッツダンス❗️   
2344      Creepy Nutsの武道館ライブを、配信で見たよ♪   
2345                    珍しいチューナーを見つけた   
2346  パピコクレさんに捧ぐアリア（歌：Paprikachordさん）   
2347        今をときめく現代アーティストとは？【自己紹介続き】   

                                                content  \
0     今日は午前中だけ仕事して、午後医者に行き、夕方はホームレスのお友達からお寿司をおごってもらっ...   
1     父も、母も、もう他界してしばらくが経つ。私も、もう、いい歳で。父も母も、生きていればそれなり...   
2     　最近、たまたま観たのですが『趣味どきっ！』の“スゴ楽” 家事への道シリーズが良かったんです...   
3     新しい服を買わないようにしようと決めて3年ほどたった。3年前ぐらいに、断捨離とか、家の整理と...   
4     父方の祖父母の家には、伯父と伯母と従兄弟が一緒に暮らしていて、台所には冷蔵庫と茶箪笥が2台ず...   
...                                                 ...   
2343  今回、ナゴコンの皆さんと、沢山の方々に助けて頂いて、出来上がって来ました。”緑文化小劇場＆ナ...   
2344  　　12日夜、Creepy　Nuts（クリーピーナッツ）という、ヒップホップのグループの武道...   
2345  ども、キャンピングミュージシャンの山木将平です。　最近ギターのチューナーを無くしてしまいどー...   
2346  「パピコクレさんに捧ぐアリア」をPaprikachordさんに歌っていただきました。「パピコ...   
2347  こんばんは。なぜ、こんばんは、って？それはこの記事を読めばわかるかもしれないです。さて、今回...   

                                                   tags  \
0                                             ['#毎日更新']   
1     ['#日記', '#エッセイ', '#母', '#父', '#ほぼ毎日note', '#やさ...   
2                     ['#毎日note', '#習慣', '#テレビ', '#掃除']   
3                                              ['#断捨離']   
4                  ['#介護', '#母', '#認知症', '#父', '#引っ越し']   
...                                                 ...   
2343                                    ['#ピアノ', '#映像']   
2344                                  ['#音楽', '#ライブ配信']   
2345                               ['#ギター', '#ミュージシャン']   
2346                         ['#音楽', '#DTM', '#オリジナル曲']   
2347                                          ['#自己紹介']   

                                                doc_vec  \
0     [-0.6413622315797844, -0.02762089093218069, -0...   
1     [-0.21704280540967982, 0.06023082480144997, -0...   
2     [-0.6624432352820425, -0.054146641178606014, -...   
3     [-0.6314828735735987, -0.09158760018281703, -0...   
4     [-0.522198764722776, -0.01959150434377851, -0....   
...                                                 ...   
2343  [-0.8237114698033441, -0.12204698043113404, -0...   
2344  [-0.48791739515120713, -0.38404660005594643, -...   
2345  [-0.9868878505362549, -0.032979069012369897, -...   
2346  [-0.9321060173370889, -0.046223862741706555, -...   
2347  [-0.5622327147551426, -0.12416846316262353, -0...   

                             labels  
0                               [9]  
1     [0, 1, 565, 1068, 1146, 1382]  
2                [3, 160, 478, 779]  
3                             [421]  
4       [199, 565, 890, 1068, 1302]  
...                             ...  
2343                    [169, 1051]  
2344                       [8, 708]  
2345                    [148, 1399]  
2346                  [8, 103, 488]  
2347                           [27]  

[2348 rows x 5 columns]

In [6]:
# Getting and formatting the inputs (doc_vec) and outputs (multilabel) from dataframe 
X = np.array([np.array(eval(elem)) for elem in df["doc_vec"]])
Y = np.array([eval(elem) for elem in df["labels"]])
Y = MultiLabelBinarizer().fit_transform(Y)
print(X)
print(Y)

[[-0.64136223 -0.02762089 -0.31077059 ... -0.29829604 -0.53742901
   0.18948011]
 [-0.21704281  0.06023082 -0.55525767 ... -0.31878226 -0.48156569
  -0.25063461]
 [-0.66244324 -0.05414664 -0.38273322 ... -0.5921418  -0.41440249
   0.13317313]
 ...
 [-0.98688785 -0.03297907 -0.57405516 ... -0.70934571 -0.44303308
  -0.01264584]
 [-0.93210602 -0.04622386 -0.6457347  ... -0.4526942  -0.18084227
   0.18225742]
 [-0.56223271 -0.12416846 -0.67268819 ... -0.5615323  -0.30514376
   0.01940162]]
[[0 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


<ipython-input-6-85081fb70f71>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Y = MultiLabelBinarizer().fit_transform(np.array([eval(elem) for elem in df["labels"]]))


In [13]:
print(X.shape,Y.shape)

(2348, 200) (2348, 1279)


In [14]:
# Separating the train and test data
# It is commentend for now since the data size is small
# x_train, x_test,y_train, y_test = train_test_split(X,Y)

In [15]:
# Defining our model (in this case I am using a Gaussian Naive Bayes Classifier) 
# and updating it for multilabeling
model = OneVsRestClassifier(GaussianNB())
# Fitting the model with data
model.fit(X,Y)

OneVsRestClassifier(estimator=GaussianNB())

In [16]:
# Testing the model
y_pred = model.predict(x_test)
y_pred_proba = model.predict_proba(x_test)

In [31]:
print(y_pred)
print(y_test)
idx = 1
N = 5
a = np.where(y_test[idx] == 1)
print(a)
print(y_pred_proba[idx].argsort()[-5:][::-1])

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]]
(array([ 215,  404, 1144]),)
[ 65 215  31 404  10]


In [54]:
# Function to get the more likely N labels
def predict(model,x,N=5):
    tmp = model.predict_proba(x)
    pred = np.array([elem.argsort()[-N:][::-1] for elem in tmp])
    return pred

In [57]:
# Testing the model
m = 10 # number of test cases to take
pred = predict(model,x_test[:m])
test = [list(np.where(elem==1)[0]) for elem in y_test[:m]]
print(pred)
for elem in test:
    print(elem)

[[  97   35   12   17    9]
 [  65  215   31  404   10]
 [ 759  539   57   37  112]
 [1260  657  719   51   22]
 [ 717   21   35   59    2]
 [ 463 1183   23   22   42]
 [  43  381  354   65   86]
 [ 911   85  106   55    2]
 [  94   19    4    2    3]
 [ 955  556  102   59   95]]
[97]
[215, 404, 1144]
[539, 759]
[22, 51, 172, 657, 719, 1260]
[0, 1, 3, 6, 9, 17, 21]
[0, 1, 3, 25, 38, 463, 511, 1183]
[43]
[85, 911]
[1, 8, 19, 94, 315]
[95, 556, 955]
